name: CI-Pipeline

on:
  workflow_call:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup environment
        uses: './.github/actions/setup-environment'

      - name: run unit test
        run: pnpm test:unit
